no PACKAGE & no quotes for compiled function name
exception: monoMDS needs quotes, probably because it has mixed case
and .Fortran calls are cast to lower case